### ISSUE TITLE
NodeSource getRelation issue in laravel 5.6

### ISSUE THREAD

**Issue by subhasundardass** [NuclearCMS/Hierarchy#1]
I am getting a problem in NodeSource, In Laravel 5.6 getRelation($name) in Builder class, Code has benn changed, I can configure the existing code on it, 

OLDER LARAVEL :
return $this->getModel()->{$name}();

NEW LARAVEL : 
return $this->getModel()->newInstance()->$name();

If I omit the newInstance its run well, But I don't want to change the Core code of Laravel.
Can you please give me a solution...

Skype : infolinematrix
mail : infolinematrix@gmail.com

**Comment by Hyleeh** [comment]
Hi, improvements on this package is scheduled for February 2019, but you are most welcome to create a pull request in the meanwhile

Best,
